=== HaxeFoundation/haxelib/schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
	"description": "A haxelib project",
	"type": "object",
	"properties": {
		"name": { "$ref": "#/definitions/name" },
		"license": {
			"description": "The open source license under which the project is licensed",
			"enum": ["GPL", "LGPL", "BSD", "Public", "MIT"]
		},
		"tags": {
			"type": "array",
			"items": {
				"type": "string"
			},
			"uniqueItems": true
		},
		"description": {
			"type": "string"
		},
		"classPath": {
			"description": "The folder in the package which contains the source files for this haxelib",
			"type": "string"
		},
		"contributors": {
			"type": "array",
			"items": { "$ref": "#/definitions/name" },
			"minItems": 1,
			"uniqueItems": true
		},
		"releasenote": {
			"type": "string"
		},
		"version": { "$ref": "#/definitions/semver" },
		"url": {
			"type": "string",
			"format": "uri"
		},
		"dependencies": {
			"type": "object",
			"additionalProperties": { "$ref": "#/definitions/dependancyVersion" }
		}
	},
	"additionalProperties": true,
	"required": ["name", "license", "releasenote", "contributors", "version"],
	"definitions": {
		"name": {
			"description": "The name of a haxelib project or user",
			"type": "string",
			"minLength": 2,
			"pattern": "^[A-Za-z0-9_.-]{2,}$"
		},
		"semver": {
			"type": "string",
			"pattern": "^([0-9]+)\\.([0-9]+)\\.([0-9]+)(-(alpha|beta|rc)(\\.([0-9]+))?)?$"
		},
		"dependancyVersion": {
			"oneOf": [
				{ "$ref": "#/definitions/semver" },
				{
					"type": "string",
					"maxLength": 0
				}
			]
		}
	}
			
}

=== HaxeFoundation/haxelib/test/libraries/libFoo/haxelib.json
{
	"name": "Foo",
	"url" : "http://example.org",
	"license": "GPL",
	"tags": ["foo", "test"],
	"description": "This project is an example of an haxelib project",
	"version": "0.1.0-alpha.0",
	"releasenote": "Initial release, everything is working correctly",
	"dependencies": {
		"Bar": ""
	},
	"contributors": ["Foo"]
}

=== HaxeFoundation/haxelib/test/libraries/libFooHgDep/haxelib.json
{
	"name": "Foo",
	"url" : "http://example.org",
	"license": "GPL",
	"tags": ["foo", "test"],
	"description": "This project is an example of an haxelib project",
	"version": "1.0.0",
	"releasenote": "Initial release, everything is working correctly",
	"dependencies": {
		"Bar": "hg:./libraries/libBar"
	},
	"contributors": ["Foo"]
}

=== HaxeFoundation/haxelib/haxelib.json
{
	"name": "haxelib",
	"url" : "https://lib.haxe.org/documentation/",
	"license": "MIT",
	"tags": ["haxelib", "core"],
	"description": "The haxelib client",
	"classPath": "src",
	"version": "4.2.0",
	"releasenote": " * Add `state save` and `state load` commands (#610)\n * Exit with error when hxml install fails (#625)\n * Allow compiling client with hxcpp target (#643)\n * Get compiler version for run scripts lazily (#646)\n * Change the order of haxelib git submodule installation (#638)\n * Fix crashes with git commands on Windows (#642)\n * Disallow library submissions containing .git folders (#664)",
	"contributors": ["HaxeFoundation", "back2dos", "ncannasse", "jason", "Simn", "nadako", "andyli"],
	"dependencies":{
		"hx3compat": "",
		"hx4compat": "",
		"crypto": ""
	}
}
